directive @auth on FIELD | FIELD_DEFINITION
directive @hasRole(role: [String]) on FIELD | FIELD_DEFINITION
scalar MXCurrency
scalar Upload

interface MutationResponse {
  code: String!
  success: Boolean!
  message: String!
}

interface Response {
  totalCount: Int!
}

type Query
type Mutation
